- id: commitlint
  name: commitlint
  description: "😉 Use gitmoji commit in your workflow"
  entry: commitlint -e $GIT_PARAMS
  language: node
  types_or: [javascript, typescript]
  args: []
  require_serial: false
